## This set of functions allows users to cache the inverse of a matrix. 
## The first function creates the cache and the second retrives it. 


## makeCacheMatrix()
## This function creates functions that together cache the inverse of a matrix. 
## It takes a single matrix as its only argument and returns a list of four functions.

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setinv <- function(solve) m <<- solve
  getinv <- function() m
  list(set = set, get = get,
       setinv = setinv,
       getinv = getinv)
}


## cachesolve()
## This function takes the the list of functions generated by makeCacheMatrix()
## and returns the cached inverse matrix. 

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  m <- x$getinv()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setinv(m)
  m
}
